# Generated by Django 6.0.1 on 2026-01-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('museum', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
