# Generated by Django 6.0.1 on 2026-01-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=20)),
                ('museum', models.CharField(max_length=100)),
                ('visit_date', models.DateField()),
                ('slot', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('payment_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
