# Generated by Django 6.0.1 on 2026-01-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_booking_id_alter_booking_museum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='CONFIRMED', max_length=20),
        ),
    ]
